name: streptopelia_orientalis
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^3.2.1 # 状态管理核心
  riverpod_annotation: ^4.0.2 # 注解支持

  # 网络请求
  dio: ^5.9.0 # HTTP 客户端

  # UI 组件
  flutter_screenutil: ^5.9.3 # 屏幕适配
  salomon_bottom_bar: ^3.3.2 # 底部导航栏
  liquid_glass_renderer: ^0.2.0-dev.4 # 液态玻璃渲染
  liquid_tabbar_minimize: ^1.0.9 # 动态导航栏
  modal_bottom_sheet: ^3.0.0 # 底部弹框
  flutter_smart_dialog: ^4.9.8+9 # 智能弹框
  contribution_heatmap: # Github 热点图
    path: packages/contribution_heatmap
  fl_chart: ^1.1.0 # 图表库
  material_shapes: ^0.0.2 # 形状绘制
  blobs: ^2.0.0 # 流体形状
  emoji_picker_flutter: ^4.4.0 # Emoji 选择器
  dynamic_color: ^1.8.1 # 动态取色
  cupertino_icons: ^1.0.8 # iOS 风格图标

  # 数据库
  drift: ^2.30.1 # ORM 数据库
  drift_flutter: ^0.2.8 # Flutter 集成
  drift_db_viewer: ^2.1.0 # 调试查看器
  hive_ce: ^2.19.3 # 轻量 NoSQL
  hive_ui: ^1.0.14 # Hive 可视化
  hive_ce_flutter: ^2.3.4 # Hive Flutter 适配
  path_provider: ^2.1.5 # 路径获取

  # 系统功能
  share_plus: ^12.0.1 # 系统分享
  local_auth: ^3.0.0 # 生物识别验证

  # 路由
  go_router: ^17.1.0  # 声明式路由

  # 国际化
  intl: ^0.20.2 # 国际化基础
  easy_localization: ^3.0.8 # 便捷国际化

  # 日志
  logger: ^2.6.2 # 日志打印

  # 模型
  freezed_annotation: ^3.1.0 # 不可变类注解
  json_annotation: ^4.10.0 # JSON 序列化注解

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 构建工具
  build_runner: any # 代码生成运行器
  flutter_lints: any # 代码规范检查

  # 资源生成
  rename_app: any # 应用重命名
  flutter_launcher_icons: any # 图标生成
  flutter_native_splash: any # 启动屏生成

  # 代码生成器
  riverpod_generator: any # Riverpod 代码生成
  drift_dev: any # Drift 代码生成
  freezed: any # 不可变类生成
  json_serializable: any # JSON 序列化生成

flutter:
  uses-material-design: true
  assets:
    - assets/icon/streptopelia_orientalis.png
    - assets/translations/
    - assets/json/record.json
